name: Build and Publish

on:
  push:
    branches: [ master ] # 或者你使用的默认分支名称
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # 使用实际存在的最新版本

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish self-contained executable
      run: dotnet publish --configuration Release --runtime win-x64 --self-contained true /p:PublishSingleFile=true --output published-app
      # 如果你的目标是 Linux 或 macOS，可以将 `--runtime win-x64` 更改为如 `linux-x64` 或 `osx-x64`

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3 # 更新为 v3 版本
      with:
        name: published-application
        path: ./published-app
